[package]
name = "hdfs"
version = "0.0.4"

build = "build.rs"

[lib]
name = "hdfs"
path = "src/lib.rs"

[dependencies]
itertools = "0.4.1"
libc = "0.1.10"
log = "0.3.2"
url = "0.2.37"

[build-dependencies]
gcc = "0.3.17"
